apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: dev
type: Opaque
data:
  mysql-root-password: cm9vdDEyMzQ=
  mysql-user: dGVzdA==
  mysql-user-password: dGVzdDEyMzQ=
  mysql-database: aWRsZV9nYW1l
