apiVersion: v1
kind: Secret
metadata:
  name: game-server-secret
  namespace: dev
type: Opaque
stringData:
  ConnectionStrings__MySql: "Server=mysql-svc-hl;Port=3306;Database=idle_game;Uid=test;Pwd=test1234;"
  ConnectionStrings__Redis: "redis-svc-hl:6379,defaultDatabase=0"

