apiVersion: v1
kind: Service
metadata:
  name: game-server-svc-np
  namespace: dev
spec:
  type: NodePort
  selector:
    app: game-server
  ports:
    - nodePort: 32001
      port: 8080
      targetPort: 8080

